version: '3'

services:
  db:
    container_name: cp-notify
    image: postgres:14.3
    restart: always

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports:
      - 5432:5432

    volumes:
      - ./data:/var/lib/postgresql/data